@echo off
setlocal enabledelayedexpansion

set /p nomeCartella="Inserisci il nome della cartella per il progetto FiveM: "
set "desktop=%USERPROFILE%\Desktop"
set "cartellaFivem=%desktop%\%nomeCartella%"

mkdir "!cartellaFivem!"

(
    echo fx_version 'cerulean'
    echo game 'gta5'
    echo author 'ls_automanifest'
    echo description 'Batch File Auto Generated by lowsime'
) > "!cartellaFivem!\fxmanifest.lua"

set /p aggiungiClient="Vuoi aggiungere un file client? (s/n): "
if /i "!aggiungiClient!"=="s" (
    mkdir "!cartellaFivem!\client"
    echo -- Auto generated manifest by ls_createmanifest > "!cartellaFivem!\client\main.lua"
    echo client_script 'client/*.lua' >> "!cartellaFivem!\fxmanifest.lua"
)

set /p aggiungiServer="Vuoi aggiungere un file server? (s/n): "
if /i "!aggiungiServer!"=="s" (
    mkdir "!cartellaFivem!\server"
    echo -- Auto generated manifest by ls_createmanifest > "!cartellaFivem!\server\main.lua"
    echo server_script 'server/*.lua' >> "!cartellaFivem!\fxmanifest.lua"
)

set /p aggiungiShared="Vuoi aggiungere un file shared? (s/n): "
if /i "!aggiungiShared!"=="s" (
    mkdir "!cartellaFivem!\shared"
    echo -- Auto generated manifest by ls_createmanifest > "!cartellaFivem!\shared\main.lua"
    echo shared_script 'shared/*.lua' >> "!cartellaFivem!\fxmanifest.lua"
)

echo Cartella creata con successo in "!cartellaFivem!"
pause
endlocal
